import { useQuery } from "@tanstack/react-query";
// Import our new API client
import { api } from "@/lib/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText, Download } from "lucide-react";
import { toast } from "sonner";

// This component no longer needs props.
export const TaxDocumentsTab = () => {
  const { data: documents, isLoading } = useQuery({
    // Simplified query key
    queryKey: ["my-tax-documents"],
    queryFn: async () => {
      // Define the expected response shape
      type DocumentsResponse = {
        documents: any[];
      };
      
      // Call our new API endpoint
      const data = await api.get<DocumentsResponse>("tax-documents");
      return data.documents;
    },
  });

  const handleDownload = (document: any) => {
    toast.info("Document download will be implemented soon");
  };

  if (isLoading) {
    return <Skeleton className="h-[400px] w-full" />;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Tax Documents</h3>
      </div>

      {documents && documents.length > 0 ? (
        <div className="grid gap-4">
          {documents.map((doc: any) => (
            <Card key={doc.id} className="hover:shadow-md transition-shadow">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="bg-primary/10 p-3 rounded-lg">
                      <FileText className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <h4 className="font-semibold">{doc.document_type}</h4>
                      <p className="text-sm text-muted-foreground">
                        FY {doc.financial_year}
                      </p>
                      <p className="text-xs text-muted-foreground mt-1">
                        Generated on {new Date(doc.generated_at).toLocaleDateString("en-IN")}
                      </p>
                    </div>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(doc)}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <FileText className="mr-2 h-5 w-5 text-primary" />
              No Tax Documents Available
            </CardTitle>
            <CardDescription>
              Your Form 16 and other tax documents will appear here once generated by HR
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="bg-muted/50 p-4 rounded-lg space-y-2">
              <p className="text-sm font-medium">Available Documents Include:</p>
              <ul className="text-sm text-muted-foreground space-y-1 ml-4">
                <li>• Form 16 (TDS Certificate)</li>
                <li>• Form 16A (TDS on Income other than Salary)</li>
                <li>• Annual Tax Statement</li>
                <li>• Investment Proofs</li>
              </ul>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

